### ISSUE TITLE
Software Development Agreement

### ISSUE THREAD

**Issue by adulbrich** [radiantlab/HDRICalibrationTool#21]
To be compiled in Google Docs until Starlight site is setup

**Comment by shantimorrell** [comment]
(Draft in shared drive)

First group draft has been compiled using Jacob's and Shanti's individual drafts. 

I tried to mostly add everything from these two drafts, combining where there were similarities. Where there was differing content in principles, I mostly went with whatever leaned towards the most accountability within our team (e.g. everyone has to review a pull request, rather than only one person). 

Elsewhere, there are a couple of places where we might need to discuss how we'd like to go about things. See some brief comments in the google doc (although they were more meant for me - to remind myself what to ask/review).

Roles and the Release Cycle are the two areas with the least clarity right now.

Feel free to review it and make comments, edit it, or let me know if you disagree with something or think it should be different!
